name: Scan for vulnerabilities in dependencies

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["*"]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Trivy vulnerability scanner in fs mode
        uses: aquasecurity/trivy-action@0.28.0
        with:
          scan-type: "fs"
          scan-ref: "."
          exit-code: 1
          scanners: "vuln"
          trivy-config: trivy.yaml

      - name: Verify that no vulnerabilities were found
        if: failure()
        run: |
          echo "High or Critical level vulnerabilities were found. Please consider fixing them."
          exit 1
